#include "topologos/codegen/generator.hpp"
#include "topologos/ast/node.hpp" 
#include "topologos/topology/simplex.hpp"

#include <iostream>
#include <regex>
#include <set>

namespace topologos::codegen {

    void CppGenerator::generate(const topologos::ast::Node* root) {
        if (!root) return;

        // ProgramNode로 시작
        if (auto program = dynamic_cast<const topologos::ast::ProgramNode*>(root)) {
            visit_program(program);
        }
    }

    void CppGenerator::visit_program(const topologos::ast::ProgramNode* node) {
        mermaid_ss_ << "graph TD;\n";
        mermaid_ss_ << "    %% Generated by TopoLogos Compiler\n";
        
        // [Fix] children -> domains (구체적 타입 순회)
        for (const auto& domain : node->domains) {
            // unique_ptr/shared_ptr로 가정하고 get() 사용
            // 만약 스마트 포인터가 아니라면 &domain으로 변경 필요
            visit_domain(domain.get());
        }
    }

    void CppGenerator::visit_domain(const topologos::ast::DomainNode* node) {
        mermaid_ss_ << "    subgraph " << node->name << "\n";
        
        // [Fix] children -> axioms
        for (const auto& axiom : node->axioms) {
            visit_axiom(axiom.get());
        }
        
        mermaid_ss_ << "    end\n";
    }

    void CppGenerator::visit_axiom(const topologos::ast::AxiomNode* node) {
        mermaid_ss_ << "    " << node->name << "[Axiom: " << node->name << "]\n";
        
        // [Fix] children -> rules
        for (const auto& rule : node->rules) {
            visit_rule(rule.get());
            // 시각화: Axiom -> Rule 연결선
            mermaid_ss_ << "    " << node->name << " --> " << rule->name << "\n";
        }
    }

    void CppGenerator::visit_rule(const topologos::ast::RuleNode* node) {
        mermaid_ss_ << "    " << node->name << "(Rule: " << node->name << ")\n";
    }

    // ---------------------------------------------------------
    //  Knowledge Transpiler (JSON -> C++ Header)
    // ---------------------------------------------------------

    std::string CppGenerator::sanitize_name(const std::string& raw) {
        std::string out;
        bool capitalize_next = true;
        for (char c : raw) {
            if (isalnum(c)) {
                if (capitalize_next) {
                    out += toupper(c);
                    capitalize_next = false;
                } else {
                    out += c;
                }
            } else {
                capitalize_next = true;
            }
        }
        if (out.empty()) return "UnknownEntity";
        if (isdigit(out[0])) return "_" + out;
        return out;
    }

    std::string CppGenerator::transpile_knowledge(const std::vector<nlohmann::json>& verified_facts) {
        std::stringstream ss;
        std::set<std::string> defined_types;

        ss << "// \n";
        ss << "//  🛡️ GENERATED BY TOPOLOGOS COMPILER\n";
        ss << "//  DO NOT EDIT. THIS FILE REPRESENTS THE IMMUTABLE TRUTH.\n";
        ss << "// \n";
        ss << "#pragma once\n";
        ss << "#include <string>\n";
        ss << "#include <vector>\n";
        ss << "#include <expected> // C++23 Feature\n\n";
        
        ss << "namespace Reality {\n\n";

        // 1. Entities as Types
        ss << "    // [1] Entities as Types (Existence Proof)\n";
        for (const auto& fact : verified_facts) {
            if (fact.contains("attributes") && fact["attributes"].contains("structure")) {
                auto structure = fact["attributes"]["structure"];
                if (structure.contains("dependency_sources")) {
                    for (const auto& source : structure["dependency_sources"]) {
                        if (source.is_string()) {
                            std::string type_name = sanitize_name(source.get<std::string>());
                            if (defined_types.find(type_name) == defined_types.end()) {
                                ss << "    struct " << type_name << " { \n";
                                ss << "        static constexpr const char* id = \"" << source.get<std::string>() << "\";\n";
                                ss << "    };\n";
                                defined_types.insert(type_name);
                            }
                        }
                    }
                }
            }
        }
        
        ss << "\n    // [2] Relations as Functions (Causality Proof)\n";
        for (const auto& fact : verified_facts) {
             if (fact.contains("attributes") && fact["attributes"].contains("structure")) {
                auto structure = fact["attributes"]["structure"];
                if (structure.contains("dependency_sources")) {
                    auto sources = structure["dependency_sources"];
                    if (sources.size() >= 2 && sources[0].is_string() && sources[1].is_string()) {
                        std::string type_a = sanitize_name(sources[0].get<std::string>());
                        std::string type_b = sanitize_name(sources[1].get<std::string>());
                        
                        ss << "    // Logic: If " << type_a << " exists, is " << type_b << " implied?\n";
                        ss << "    [[nodiscard]]\n";
                        ss << "    inline auto derive_" << type_b << "_from_" << type_a 
                           << "(const " << type_a << "& context) -> std::expected<" << type_b << ", std::string> {\n";
                        
                        float score = fact.value("score", 0.0f);
                        if (score > 80.0f) {
                            ss << "        return " << type_b << "{};\n";
                        } else {
                            ss << "        return std::unexpected(\"Weak Causality (Score: " << score << ")\");\n";
                        }
                        ss << "    }\n\n";
                    }
                }
             }
        }

        // [New] 위상수학적 필터링
        ss << "    // 🛡️ Topological Verification: Only 2-Simplex (Triangle) or higher are promoted to Types.\n";

        for (const auto& fact : verified_facts) {
            if (fact.contains("attributes") && fact["attributes"].contains("structure")) {
                auto structure = fact["attributes"]["structure"];
                
                // 출처 목록 가져오기
                std::vector<std::string> sources;
                if (structure.contains("dependency_sources")) {
                    for (const auto& s : structure["dependency_sources"]) {
                        if (s.is_string()) sources.push_back(s.get<std::string>());
                    }
                }

                // [Core Logic] 차원 계산 (숫자 점수 대체!)
                int dim = topologos::topology::SimplexEngine::calculate_dimension(sources);
                std::string entity_name = sanitize_name(fact.value("id", "Unknown"));

                if (dim >= 2) {
                    // [2-Simplex] Face -> "Fact" (강한 타입)
                    ss << "    // [Dimension " << dim << "] Solid Fact verified by " << sources.size() << " sources.\n";
                    ss << "    struct " << entity_name << " {\n";
                    ss << "    #define REALITY_HAS_" << entity_name << " 1\n";
                    ss << "        static constexpr int topology_dimension = " << dim << ";\n";
                    ss << "        // Invariant: This fact is structurally stable.\n";
                    ss << "    };\n";

                    // 인과관계 함수 생성 (강한 연결)
                    if (sources.size() >= 2) {
                        std::string ctx = sanitize_name(sources[0]);
                        ss << "    inline auto derive_" << entity_name << "(const " << ctx << "& context) -> " << entity_name << " { return {}; }\n\n";
                    }

                } else if (dim == 1) {
                    // [1-Simplex] Edge -> "Correlation" (약한 타입 - Optional)
                    ss << "    // [Dimension 1] Weak Correlation (Edge only).\n";
                    ss << "    // struct " << entity_name << "; // Forward declaration only\n";
                    ss << "    // using Maybe" << entity_name << " = std::optional<" << entity_name << ">;\n\n";
                } 
                // Dimension 0은 노이즈로 간주하여 코드 생성 안 함 (Pruning)
            }
        }

        ss << "} // namespace Reality\n";
        return ss.str();
    }
}