#include "../../include/topologos/codegen/generator.hpp"
#include <iostream>

namespace topologos::codegen {

    using namespace ast;

    std::string CppGenerator::generate(const ProgramNode* program) {
        output_.str("");
        mermaid_buffer_.str("");
        
        output_ << "// Generated by TopoLogos Engine\n";
        output_ << "#include <iostream>\n\n";

        if (!program) return "";

        // AST 순회
        for (const auto& domain : program->domains) {
            visit_domain(domain.get());
        }

        return output_.str();
    }

    void CppGenerator::visit_domain(const DomainNode* node) {
        output_ << "namespace " << node->name << " {\n";
        
        // Mermaid: Subgraph for Domain
        mermaid_buffer_ << "  subgraph " << node->name << "\n";

        for (const auto& axiom : node->axioms) {
            visit_axiom(axiom.get());
        }

        mermaid_buffer_ << "  end\n";
        output_ << "} // namespace " << node->name << "\n\n";
    }

    void CppGenerator::visit_axiom(const AxiomNode* node) {
        output_ << "  // Axiom: " << node->name << "\n";
        
        // Mermaid: Node for Axiom
        mermaid_buffer_ << "    " << node->name << "[Axiom: " << node->name << "]\n";

        for (const auto& rule : node->rules) {
            visit_rule(rule.get());
            // Mermaid: Rule connection
            mermaid_buffer_ << "    " << node->name << " --> " << rule->name << "\n";
        }
    }

    void CppGenerator::visit_rule(const RuleNode* node) {
        output_ << "  // Rule: " << node->name << "\n";
        
        // C++ Function generation (Mock)
        output_ << "  bool check_" << node->name << "() {\n";
        output_ << "      return true; // Logic implementation placeholder\n";
        output_ << "  }\n";

        // Mermaid: Node for Rule
        mermaid_buffer_ << "    " << node->name << "(Rule: " << node->name << ")\n";
    }

} // namespace topologos::codegen